import Drawer from "@/components/Drawer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ubuntu-regular`}
      >
        {children}
        <Drawer />
      </body>
    </html>
  );
}
